[package]
name = "rustingpixels"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4"
image = "0.23"
rand = "0.8.4"
rand_distr = "0.4.3"
noise = "0.7"
scarlet = "1.1"
crossbeam = "0.8"
nalgebra = "0.30.1"
